### PR TITLE
Adding hot-loader features to the boilerplate

### PR DESCRIPTION
**Pull request by llaine**
I think the ability to tweak component in real time are very convenient and should be a basic feature in boilerplate. It does not really complexify the boilerplate. 

For more informations about the react-hot features [the doc](https://github.com/gaearon/react-hot-loader)

If you did not already seen this, a great [conference](https://www.youtube.com/watch?v=xsSnOQynTHs) on the subject by the creator of redux. 

Great book btw.

### CODE REVIEW

**Comment by cassiozen** [comment]
Hi llaine,

First of all, thanks a lot for your pull request. I agree with you when you say that "the ability to tweak component in real time are very convenient", but I'd like to further discuss before merging.

The first thing that worried me is that "React Hot Loader" is being phased away in favor of the React Transform (as described [here](https://github.com/gaearon/react-hot-loader)). 

Secondly, I'm on the cusp of releasing the Webpack appendice, and it will come with a more complete React boilerplate, including html plugin, CSS modules and react-transform-hmr. Maybe it's interesting from the point of view of a beginner to leave this boilerplate with as little files and configurations as possible (a really bare-bones starting point, with low cognitive load) and offer a different, more complete and sophisticated boilerplate for when the reader is ready.

What do you think?

**Comment by llaine** [comment]
My bad, I didn't seen the deprecation notice on the hot-loader repo, it make sense not to merge the PR then. 

Putting this in a more complex boilerplate and leave this one as a bare-bones starting point is a good idea :+1: 

When this more complex boilerplate will be available ?

**Comment by cassiozen** [comment]
Just published them:
The Appendix A (covering Webpack) is available [here](http://www.pro-react.com/materials/), and the advanced boilerplate is now a separate github [repo](https://github.com/pro-react/react-app-advanced-boilerplate).
=]

**Comment by llaine** [comment]
Awesome thank's !

**Pull request closed without merging**
